# Change these first
owner: ec-snee # Your GitHub organization or username, where this repository lives
repo: gobeyond-uptime # The name of this repository

sites:
  - name: Gobeyond API
    url: https://api.gobeyond-project.eu/health-check
    __dangerous__body_down_if_text_missing: 'Status: OK'
  - name: Gobeyond Dev API
    url: http://136.156.139.134/health-check
    __dangerous__body_down_if_text_missing: 'Status: OK'
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /gobeyond-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Gobeyond Uptime
  introTitle: Gobeyond API Uptime
  introMessage: Uptime checked for the gobeyond project's API service
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
